### ISSUE TITLE
Enhance Result Cards

### ISSUE THREAD

**Issue by mbwatson** [NeuroBridge/Search-Portal#20]
We want to spruce up the result cards with a bit more detail for the user.

- [x] change button text: VIEW -> VIEW FULL TEXT
- [ ] show author block (this awaits @HowardLander's scraping service)
- [x] show score

**Comment by mbwatson** [comment]
@HowardLander i've scaffolded out a space to show authors and scores in the publication/result cards.

![Screenshot from 2022-08-02 09-39-25](https://user-images.githubusercontent.com/6019870/182388758-f3313287-7e72-484b-b32f-cce2f8a9039e.png).

the similarity scores are already coming through. should we get together sometime soon and plan out surfacing snippets and authors?

**Comment by HowardLander** [comment]
Sure.  What times work for you?

________________________________

**Comment by mbwatson** [comment]
I'll get in touch this week to chat about it.

**Comment by mbwatson** [comment]
obsolete with ui changes since this issue was created.
