### ISSUE TITLE
Contact View

### ISSUE THREAD

**Issue by mbwatson** [NeuroBridge/Search-Portal#21]
We want a contact view with some contact information and a contact form. This form should consist of just a few fields:

- Subject, text, required
- Name, text, optional
- Email, text, optional
- Message Body, textarea, required

**Comment by HowardLander** [comment]
We need to think about where the data we get from the contact form is going to be stored.  Could we use a Google Form for this?

**Comment by mbwatson** [comment]
@HowardLander yep, we could use a google form.

**Comment by mbwatson** [comment]
https://github.com/NeuroBridge/Search-Portal/issues/32
