### ISSUE TITLE
neuroquery query contains all top level terms

### ISSUE THREAD

**Issue by Woozl** [NeuroBridge/Search-Portal#41]
Is this the desired behavior?

![image](https://user-images.githubusercontent.com/16181779/218114812-4ce77e46-b3d8-403f-8ba0-91eff61ebc21.png)

The NQ string contains all of the top level terms, regardless of what their toggle selector is on:

![image](https://user-images.githubusercontent.com/16181779/218115133-142591c5-98f0-4cf7-a92d-abaa8d70daa1.png)

**Comment by mbwatson** [comment]
good catch. nope, this is not the desired behavior. only the selected terms should show up in the NQ query
