### ISSUE TITLE
NQ-NB Transform API Integration

### ISSUE THREAD

**Issue by mbwatson** [NeuroBridge/Search-Portal#46]
Some concepts in the NeuroBridge ontology are not terms known to the NeuroQuery API. For example, consider the concept "Abstinent," which is a concept in the NeuroBridge ontology. However, the associated term in the NeuroQuery is "Abstinence." This means we're unable to retrieve results from NeuroQuery when this concept is used! :cry: 

![image](https://user-images.githubusercontent.com/6019870/219435530-5050b0a4-05b0-4a47-b59b-b62ad705cd2f.png)

@HowardLander has written a NeuroBridge-to-NeuroQuery transformer service that receives a NeuroBridge concept and returns the associated NeuroQuery term(s) (usage details to come). This will allow us to add a layer to our search flow to capture results that would otherwise be lost by these subtle textual differences.

Exactly _where_ this layer gets integrated is still yet to be determined. Here are some ideas:
1. The QueryBuilder component is responsible for fetching the transformed terms and building the query as the user customizes their query.
2. The NQ-results-fetching function stages a series of calls, first to the NQ-transformer, the results of which are passed to the existing NQ-results-fetching function.
3. Something else.

Other ideas are limited by not knowing the full capabilities of that transformer API. I suppose that _if_ it could take an _array_ of concepts and return an _array_ of transformed NQ terms, that could be a useful extension to implement on the API side. Is it worth the effort? Not sure. So discussion is still necessary here so we can find the approach that makes the most sense.

**Comment by mbwatson** [comment]
here's an example of the current functionality of this service.

![image](https://user-images.githubusercontent.com/6019870/221594683-f5d46ae5-0130-4dd8-9b6d-4dbac741e2f9.png)

this response comes from hitting https://neurobridges.apps.renci.org/neurobridge?searchTerms=abstinent, which returns the NQ terms associated with "Abstinent," as mentioned in the original issue comment.

there are two other parameters accepted: `thresh` specifies a score threshold and `matches` limits the number of returned terms. for example, https://neurobridges.apps.renci.org/neurobridge?searchTerms=depression&thresh=1.5&matches=3 returns a maximum of three terms with thresholds at or above 1.5:

```json
{
  "data": [
    {
      "search_time": 0.015332948882132769
    },
    {
      "score": 2,
      "term": "depression",
      "term_name": "depression"
    },
    {
      "score": 1.9778383,
      "term": "depressions",
      "term_name": "depressions"
    },
    {
      "score": 1.9170433,
      "term": "depressed",
      "term_name": "depressed"
    }
  ]
}
```

**Comment by mbwatson** [comment]
@HowardLander is this the repo for the API discussed here: https://github.com/NeuroBridge/neuro-query-dense-vectors ?

**Comment by HowardLander** [comment]
Yes
________________________________
