### ISSUE TITLE
broken NeuroQuery link

### ISSUE THREAD

**Issue by mbwatson** [NeuroBridge/Search-Portal#47]
**Describe the bug**
the link to view results in NeuroQuery links to`https://neuroquery.org/query?text=undefined``

**To Reproduce**
1. Build a query & get results
2. Visit NeuroQuery results tab
3. Click "View these results at NeuroQuery.org"
4. See where it lands you

**Expected behavior**
User should go to `https://neuroquery.org/query?text=ConceptOne+ConceptTwo`

**Screenshots**
![image](https://user-images.githubusercontent.com/6019870/219469130-f1beaf50-47ee-41a3-b300-a8ef7d577fc9.png)

**Comment by Woozl** [comment]
Sorry about this one! I missed this in the refactor. Didn't realize it was also used here
