### ISSUE TITLE
Article links

### ISSUE THREAD

**Issue by mbwatson** [NeuroBridge/Search-Portal#55]
For NeuroBridge results, although the "Abstract" link and "Full Text" link each show different text, the actual links both point at the PubMed Central full text article (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6177285/).

The "Abstract" should link to PubMed instead (https://pubmed.ncbi.nlm.nih.gov/29779671/).

**Comment by mbwatson** [comment]
the NB response is an array of objects that are shaped like this:
```
{
  "title": "Relationships between abnormal neural activities and cognitive impairments in patients with drug-naive first-episode schizophrenia",
  "snippet": "Background Prior resting state functional Magnetic Resonance Imaging studies ( rs-fMRI ) via the regional homogeneity ( ReHo ) method have demonstrated inconsistent and conflicting results because of several confounding",
  "score": 3,
  "pmid": "32503481",
  "pubmed_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7275517",
  "pmcid": "PMC7275517",
  "pmc_url": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7275517"
}
```

note that `pubmed_url` and `pmc_url` are identical, and this appears to be the case for all objects in the response. this is why they are the same in the UI.

@HowardLander, should the NB results be returning different URLs for `pubmed_url` and `pmc_url`?

**Comment by HowardLander** [comment]
Yep,  the links should be different.  This is the return from @rayyuewang interface?

**Comment by rayyuewang** [comment]
Indeed, the links should be different. There must be a bug in the code. I will go and check now.

**Comment by rayyuewang** [comment]
Wait, I am confused. @mbwatson Can you confirm that the POST request endpoint is https://neurobridges-ml.renci.org/nb_translator ? The returned JSON is supposed to only have the following fields: title, abstract, pmid, pmcid, pmc_link, score, snippet. It shouldn't contain pubmed_url and pmc_url.

**Comment by Woozl** [comment]
The JSON response:

```json
{
    "abstract": "Abstract\nBackground\nStimulant use and sexual behaviors have been linked in behavioral and epidemiological studies. Although methamphetamine-related neurofunctional differences have been investigated, few studies have examined neural responses to drug and sexual cues with respect to shorter or longer term methamphetamine abstinence in individuals with methamphetamine dependence.\nMethods\nForty-nine men with shorter term methamphetamine abstinence, 50 men with longer term methamphetamine abstinence, and 47 non\u2013drug-using healthy comparison men completed a functional magnetic resonance imaging cue-reactivity task consisting of methamphetamine, sexual, and neutral visual cues.\nResults\nRegion-of-interest analyses revealed greater methamphetamine cue\u2013related activation in shorter term methamphetamine abstinence and longer term methamphetamine abstinence individuals relative to healthy comparison men in the ventromedial prefrontal cortex. A significant interaction of group and condition in the anterior insula was found. Relative to healthy comparison participants, both shorter term methamphetamine abstinence and longer term methamphetamine abstinence groups displayed greater sexual cue\u2013related anterior insula activation relative to methamphetamine cues and neutral cues, but there were no differences between shorter term methamphetamine abstinence and longer term methamphetamine abstinence groups in anterior insula responses. Subsequent whole-brain analyses indicated a group-by-condition interaction with longer term methamphetamine abstinence participants showing greater sexual-related activation in the left superior frontal cortex relative to healthy comparison men. Shorter term methamphetamine abstinence participants showed greater superior frontal cortex activation to sexual relative to neutral cues, and longer term methamphetamine abstinence participants showed greater superior frontal cortex activation to sexual relative to neutral and methamphetamine cues.\nConclusions\nThe findings suggest that abstinence from methamphetamine may alter how individuals respond to drug and sexual cues and thus may influence drug use and sexual behaviors. Given the use of methamphetamine for sexual purposes and responses to natural vs drug rewards for addiction recovery, the findings may have particular clinical relevance.\n",
    "pmc_link": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7171928",
    "pmcid": "PMC7171928",
    "pmid": "31995187",
    "score": 1.0,
    "snippet": "Abstract Background Stimulant use and sexual behaviors have been linked in behavioral and epidemiological studies . Although methamphetamine-related neurofunctional differences have been investigated , few studies have examined neural responses",
    "title": "Neurofunctional Differences Related to Methamphetamine and Sexual Cues in Men With Shorter and Longer Term Abstinence Methamphetamine Dependence"
},
```

Looks like it's just a mapping issue on the frontend. [This code](https://github.com/NeuroBridge/Search-Portal/blob/23d931c3179d5cc340a7f4385fd26418012999ec/src/components/search/context.js#L66-L74) is returning an object with both `pubmed_url` and `pmc_url` pointing to `pmc_link`:
```javascript
return data.docs.map(result => ({
  title: result.title,
  snippet: result.snippet,
  score: result.score,
  pmid: result.pmid,
  pubmed_url: result.pmc_link,
  pmcid: result.pmcid,
  pmc_url: result.pmc_link,
}))
```

**Comment by mbwatson** [comment]
ah, yes, thanks for clarifying, @Woozl!

so we're indeed only receiving the PubMed Central URL from [neurobridges-ml.renci.org/nb_translator](https://neurobridges-ml.renci.org/nb_translator).. the API does not return a PubMed URL.

**Comment by mbwatson** [comment]
is it always true that, if we know the PMID is XYZ, then https://pubmed.ncbi.nlm.nih.gov/XYZ/ is the PubMed URL?

for example, in the above copied payload, the PMID is 31995187, and this is the location on PubMed: https://pubmed.ncbi.nlm.nih.gov/31995187/.

**Comment by rayyuewang** [comment]
Yes, that's my understanding. 
And I believe we can also infer the PMC link in the same way: if the PMCID is ABC, then the PMC link is https://www.ncbi.nlm.nih.gov/pmc/articles/ABC/ . Therefore it's kind of redundant to send both pmcid and pmc_link in the response from the backend.

**Comment by mbwatson** [comment]
agreed, so we'll just extract `pmid` and `pmcid` from the response to construct links to:

- the abstract, `https://www.ncbi.nlm.nih.gov/pmc/articles/{pmcid}/`, and
- the full text, `https://pubmed.ncbi.nlm.nih.gov/{pmid}/`.
