### ISSUE TITLE
Tray for terms present in paper

### ISSUE THREAD

**Issue by Woozl** [NeuroBridge/Search-Portal#61]
We will have a file that maps pmc identifiers -> array of ontology terms in that publication. We want this list of terms to show when the user clicks a publication in the results table.  A tray should pop out and show a list of concepts.

@HowardLander let me know when you've got that file ready so I can begin work on this.

**Comment by HowardLander** [comment]
Will do.  Hoping to do it this afternoon, but may be Monday.

Howard
________________________________
From: David Glymph ***@***.***>
Sent: Friday, March 17, 2023 11:34 AM
To: NeuroBridge/Search-Portal ***@***.***>
Cc: Lander, Howard Michael ***@***.***>; Mention ***@***.***>
Subject: [NeuroBridge/Search-Portal] Tray for terms present in paper (Issue #61)


We will have a file that maps pmc identifiers -> array of ontology terms in that publication. We want this list of terms to show when the user clicks a publication in the results table. A tray should pop out and show a list of concepts.

@HowardLander<https://github.com/HowardLander> let me know when you've got that file ready so I can begin work on this.

**Comment by HowardLander** [comment]
I've sent the file off to David.  But the data is really supposed to come through the article API.  But the file should be useful for prototyping the portal GUI
________________________________
From: David Glymph ***@***.***>
Sent: Friday, March 17, 2023 11:34 AM
To: NeuroBridge/Search-Portal ***@***.***>
Cc: Lander, Howard Michael ***@***.***>; Mention ***@***.***>
Subject: [NeuroBridge/Search-Portal] Tray for terms present in paper (Issue #61)


We will have a file that maps pmc identifiers -> array of ontology terms in that publication. We want this list of terms to show when the user clicks a publication in the results table. A tray should pop out and show a list of concepts.

@HowardLander<https://github.com/HowardLander> let me know when you've got that file ready so I can begin work on this.

**Comment by mbwatson** [comment]
@HowardLander should these concepts be in the ontology? they don't appear to be.

**Comment by HowardLander** [comment]
Yes they should. Is it an issue of capitalization or spacing?

**Comment by mbwatson** [comment]
no, they're just different concepts. here's a screenshot with non-ontology concepts:
![image](https://user-images.githubusercontent.com/6019870/226720704-5c9a69f5-15d2-416b-881a-1ae4203ec8a8.png)

**Comment by HowardLander** [comment]
Huh.  I don't know.  I agree that seems weird.
________________________________

**Comment by mbwatson** [comment]
just noting here what we discussed in email...

we can go ahead and start prototyping under the assumption that the concepts in the inverted JSON will indeed be in the ontology. although not yet present, there is ongoing work to expand the ontology to include these concepts.

also, we'll need to be informed when the ontology gets updated since we're still maintaining a copy in the UI code base.
