### ISSUE TITLE
Direct links to subpages not found

### ISSUE THREAD

**Issue by mbwatson** [NeuroBridge/Search-Portal#73]
**Describe the bug**
Navigating directly to any subpage results in a 404.

**To Reproduce**
Steps to reproduce the behavior 1:
1. Go to [portal.neurobridges.org/about](https://portal.neurobridges.org/about), [portal.neurobridges.org/docs](https://portal.neurobridges.org/docs), or [portal.neurobridges.org/feedback](https://portal.neurobridges.org/feedback).

Steps to reproduce the behavior 2:
1. Go to [portal.neurobridges.org](https://portal.neurobridges.org)
2. Click on any non-Search menu item
3. Refresh the page

**Expected behavior**
It's expected that the user lands in the desired location in the app.

**Comment by Woozl** [comment]
@mbwatson this is odd, is this an issue with react-router?
