### ISSUE TITLE
Automatically expand subtree of term and descendants

### ISSUE THREAD

**Issue by mbwatson** [NeuroBridge/Search-Portal#9]

**Comment by mbwatson** [comment]
@HowardLander 

i've staged a change to address this feature request from our first meeting.

previously, the term dialog that showed the neighborhood of the term in the ontology tree. with this change, the entire subtree of descendants will be fetched from the API and rendered, fully expanded. (this issue was first in line before #5.)

note that..

1. i haven't rigorously tested this. i would appreciate any and all feedback on this feature addition, so when you're test driving things, please give this an extra few cycles of thought and let me know here if you experience any issues.
2. this makes the application take a significant performance hit, so i think we need to be sure that this functionality is absolutely necessary before committing to it.

**Comment by HowardLander** [comment]
Matt, 

I like it, but I did notice this: why are the lines crossing? See image:

![image](https://user-images.githubusercontent.com/1263277/136094368-68350f16-1bd8-4aa7-873c-dfa36de40a34.png)

**Comment by HowardLander** [comment]
OK.  Thanks.  Do we need to schedule something with Lei, or do you want to wait?
